"""empty message

Revision ID: c3be84e24040
Revises: 410b7020272e
Create Date: 2021-10-21 00:06:38.416002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3be84e24040'
down_revision = '410b7020272e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('message', sa.String(length=200), nullable=True))
    op.drop_column('contact', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('text', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('contact', 'message')
    # ### end Alembic commands ###
