"""empty message

Revision ID: cdcc50685288
Revises: c3be84e24040
Create Date: 2021-10-22 17:22:50.090815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcc50685288'
down_revision = 'c3be84e24040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('link', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'link')
    # ### end Alembic commands ###
